server:
  port: 8080
spring:
  application:
    name: MyRecipeWhisper-Backend
  datasource:
    url: jdbc:mysql://LOCALHOST:3306/myrecipewhisperdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  config:
    import: optional:file:.env

spoonacular:
  api:
    key: ${SPOONACULAR_API_KEY}
  endpoints:
    search: "https://api.spoonacular.com/recipes/complexSearch"
  defaults:
      number: 20
      addRecipeInformation: true