server:
  port: 8080
spring:
  config:
    import: optional:file:../config/env.properties
  application:
    name: MyRecipeWhisper-Backend
  datasource:
    url: jdbc:mysql://LOCALHOST:3306/myrecipewhisperdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
    show-sql: true


spoonacular:
  api:
    key: ${RAPIDAPI_KEY} 
    host: ${RAPIDAPI_HOST}
  endpoints:
    search: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/complexSearch"
  defaults:
      number: 20
      addRecipeInformation: true